import React from 'react';import{createRoot}from'react-dom/client';import'./styles.css';
import{Menu,Search,ArrowRight,Play,Wrench,Clock3,ArrowUpRight,BookOpen,ChevronRight,Package,GitBranch,Share2,Download}from'lucide-react';
import{useState}from'react';

type Project={id:string;number:string;title:string;category:string;level:string;duration:string;description:string;tags:string[];status:string;image:string};
const projects:Project[]=[
{id:'rover',number:'PROJECT 001',title:'Autonomous Mapping Rover',category:'Robotics',level:'Intermediate',duration:'3 weeks',description:'A compact rover that explores a space, measures its surroundings, and turns sensor readings into a usable map.',tags:['ESP32','LiDAR','Motors'],status:'Build guide',image:'https://images.unsplash.com/photo-1535378437320-1f7a2b8e8f7b?auto=format&fit=crop&w=1400&q=85'},
{id:'hand',number:'PROJECT 002',title:'12-Servo Robotic Hand',category:'Mechatronics',level:'Intermediate',duration:'4 weeks',description:'A multi-servo hand exploring coordinated motion, actuation, and human-inspired gestures.',tags:['Arduino','Servo','C++'],status:'In progress',image:'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=1400&q=85'},
{id:'bench',number:'PROJECT 003',title:'Connected Workbench',category:'Electronics',level:'Beginner',duration:'2 weeks',description:'A practical maker station combining sensors, power monitoring, tools, and a local control interface.',tags:['ESP32','Sensors','IoT'],status:'Published',image:'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1400&q=85'}];
const paths=[['01','Electronics Foundations','Build the fundamentals before your first serious machine.','4 projects'],['02','Robotics Builder','Move from sensors and motors to complete autonomous systems.','8 projects'],['03','Human-Robot Systems','Explore manipulation, motion, perception, and interaction.','6 projects']];
const steps=[['01','IDEA','Define the problem.'],['02','DESIGN','Turn the idea into a system.'],['03','BUILD','Make the physical thing.'],['04','FAIL','Find what breaks.'],['05','DIAGNOSE','Understand why.'],['06','IMPROVE','Change the design.'],['07','TEST','Measure the result.'],['08','DOCUMENT','Capture what happened.'],['09','SHARE','Publish the build.'],['10','REMIX','Build from it.'],['11','VERSION','Keep getting better.']];
function Navbar(){const[open,setOpen]=useState(false);return <header className="nav-wrap"><nav className="nav container"><a className="brand" href="#top"><span className="brand-mark">ID</span>IDEVRX</a><div className={'nav-links '+(open?'open':'')}><a href="#projects" onClick={()=>setOpen(false)}>Projects</a><a href="#learn" onClick={()=>setOpen(false)}>Learn</a><a href="#process" onClick={()=>setOpen(false)}>How it works</a><a href="#about" onClick={()=>setOpen(false)}>About</a></div><div className="nav-actions"><button className="icon-btn"><Search size={18}/></button><a className="nav-cta" href="#projects">Explore projects</a><button className="icon-btn mobile-menu" onClick={()=>setOpen(!open)}>{open?<span>×</span>:<Menu size={21}/>}</button></div></nav></header>}
function Hero(){return <section className="hero" id="top"><div className="container hero-grid"><div><div className="eyebrow"><i/> OPEN BUILD PLATFORM</div><h1>Ideas engineered<br/><span>into reality.</span></h1><p className="hero-lead">Real builds. Real data. Real lessons. IDEVRX is a place to document, learn, build, improve, and share physical technology.</p><div className="hero-buttons"><a className="button primary" href="#projects">Explore projects <ArrowRight size={17}/></a><a className="button secondary" href="#process"><Play size={16}/> See how it works</a></div><div className="hero-stats"><div><b>001+</b><span>Projects</span></div><div><b>03</b><span>Learning paths</span></div><div><b>100%</b><span>Build focused</span></div></div></div><div className="blueprint"><div className="bp-grid"/><span className="bp-label">FIELD NOTE / 001</span><div className="orbit o1"/><div className="orbit o2"/><div className="robot-core"><Wrench size={38}/></div><div className="bp-card ca"><small>BUILD</small><b>ROVER_001</b><span>v0.3.1</span></div><div className="bp-card cb"><small>STATUS</small><b>TESTING</b><span>72% complete</span></div><span className="coordinates">06°31' N<br/>03°23' E</span></div></div></section>}
function Projects(){return <section className="section" id="projects"><div className="container"><div className="section-head"><div><div className="eyebrow">THE BUILD LIBRARY</div><h2>Projects that show<br/><span>the whole process.</span></h2></div><p>Not just the finished object. See the design decisions, failures, tests, files, versions, and lessons behind every build.</p></div><div className="project-grid">{projects.map((p,i)=><article className={'project-card '+(i===0?'featured':'')} key={p.id}><div className="project-image"><img src={p.image} alt={p.title}/><div className="image-overlay"/><span className="project-number">{p.number}</span><span className="project-status">{p.status}</span></div><div className="project-body"><div className="project-meta">{p.category} <span>•</span> {p.level}</div><h3>{p.title}</h3><p>{p.description}</p><div className="tag-row">{p.tags.map(t=><span key={t}>{t}</span>)}</div><div className="project-foot"><span><Clock3 size={14}/> {p.duration}</span><a href="#about">View project <ArrowUpRight size={15}/></a></div></div></article>)}</div></div></section>}
function Process(){return <section className="section process-section" id="process"><div className="container"><div className="section-head"><div><div className="eyebrow">THE IDEVRX LOOP</div><h2>Failure is part of<br/><span>the documentation.</span></h2></div><p>Every build becomes more valuable when the reasoning behind it is captured. IDEVRX treats iteration as first-class engineering data.</p></div><div className="process-track">{steps.map(s=><div className="process-step" key={s[0]}><span>{s[0]}</span><strong>{s[1]}</strong><p>{s[2]}</p></div>)}</div></div></section>}
function Learning(){return <section className="section learning" id="learn"><div className="container learning-layout"><div><div className="eyebrow">LEARNING PATHS</div><h2>Learn by <span>building.</span></h2><p className="large-copy">Structured paths connect the fundamentals to real projects, so you always know what to learn next and why it matters.</p><a className="text-link" href="#projects">Browse all learning paths <ArrowRight size={16}/></a></div><div className="path-list">{paths.map(p=><a className="path" href="#projects" key={p[0]}><div className="path-num">{p[0]}</div><div><div className="path-top"><h3>{p[1]}</h3><ChevronRight size={18}/></div><p>{p[2]}</p><span><BookOpen size={14}/> {p[3]}</span></div></a>)}</div></div></section>}
function About(){const f=[[Package,'Complete files','BOMs, schematics, code, images, videos and useful build assets.'],[GitBranch,'Version history','See how a project changes from first prototype to working system.'],[Share2,'Remix culture','Start with someone else’s work, improve it, and document the result.'],[Download,'Build-ready docs','Practical documentation designed to help another person reproduce the work.']];return <section className="section about" id="about"><div className="container"><div className="about-top"><div className="eyebrow">WHY IDEVRX</div><h2>A project is more than<br/><span>the final prototype.</span></h2><p>IDEVRX turns the messy process of making physical technology into useful, reusable engineering knowledge.</p></div><div className="feature-grid">{f.map(([Icon,title,text])=><div className="feature" key={title as string}><div className="feature-icon"><Icon size={19}/></div><h3>{title as string}</h3><p>{text as string}</p></div>)}</div></div></section>}
function Footer(){return <footer className="footer"><div className="container footer-grid"><div><a className="brand" href="#top"><span className="brand-mark">ID</span>IDEVRX</a><p>Ideas engineered into reality.</p></div><div className="footer-links"><div><b>Explore</b><a href="#projects">Projects</a><a href="#learn">Learning</a><a href="#process">Process</a></div><div><b>Platform</b><a href="#about">About</a><a href="#projects">Remix</a><a href="#projects">Documentation</a></div></div></div><div className="container footer-bottom"><span>© 2026 IDEVRX</span><span>Built for people who make things.</span></div></footer>}
function App(){return <><Navbar/><main><Hero/><Projects/><Process/><Learning/><About/></main><Footer/></>};createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
